export type {
  BaseSchema,
  BoundariesConfig,
  BoundariesRulesMap,
  DependencyOutputsInput,
  EnvMode,
  EnvWildcard,
  FutureFlags,
  GlobalConfig,
  JitInput,
  OutputLogs,
  Permissions,
  Pipeline,
  RelativeUnixPath,
  RemoteCache,
  RootBoundariesConfig,
  RootSchema,
  Schema,
  StartupInput,
  UI,
  WorkspaceSchema,
} from "./generated/configuration.js";
